name: 🐛 Bug Report
description: File a bug report, if you've discovered a problem in uMarketingSuite.
title: ""
labels: ["bug"]
body:
- type: input
  id: "umsversion"
  attributes:
    label: "Which uMarketingSuite version are you using? (Please write the *exact* version, example: 10.1.0)"
    description: ""
  validations:
    required: true
- type: input
  id: "umbracoversion"
  attributes:
    label: "Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)"
    description: "Use the help icon in the Umbraco backoffice to find the version you're using"
  validations:
    required: true
- type: textarea
  id: "summary"
  attributes:
    label: "Bug summary"
    description: "Write a short summary of the bug."
    placeholder: >
      Try to pinpoint it as much as possible.
      
      Try to state the actual problem, and not just what you think the solution might be.
  validations:
    required: true
