blank_issues_enabled: false
contact_links:
    - name: ⁉️ Support Question
      url: https://www.umarketingsuite.com
      about: This issue tracker is NOT meant for support questions. If you have a question, please email us on info@umarketingsuite.com